jobs:
- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    trigger: true
  - put: docker-image
    params:
      build: git-concourse-build-docker-image

- name: use-docker-image
  public: true
  serial: true
  plan:
  - get: git-concourse-build-docker-image
    passed: [build-docker-image]
    trigger: true
  - task: use-docker-image-task
    privileged: true
    config:
    - platform: linux
      image_resource:
      - type: docker-image
        source:
        - repository: {{docker-image}}
          tag: "latest"
      inputs:
      - name: git-concourse-build-docker-image
      run:
        path: ci/tasks/package.sh

resources:
- name: git-concourse-build-docker-image
  type: git
  source:
    uri: https://github.com/bmullan-pivotal/gke-hello
    branch: master   

- name: docker-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: {{docker-image}}