platform: linux

image_resource:
  type: docker-image
  source:
    repository: {{docker-image}}
    tag: "latest"

inputs:
- name: input
outputs:
- name: output
run:
  path: source-code/ci/tasks/package.sh
